#   Copyright (c) 2022, Planet Innovation
#   436 Elgar Road, Box Hill VIC 3128 Australia
#   Phone: +61 3 9945 7510
#
#   The copyright to the computer program(s) herein is the property of
#   Planet Innovation, Australia.
#   The program(s) may be used and/or copied only with the written permission
#   of Planet Innovation or in accordance with the terms and conditions
#   stipulated in the agreement/contract under which the program(s) have been
#   supplied.

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - quality
  - test

image: $CI_REGISTRY/degraves/micropython_build_env_docker

checks:
  image: $CI_REGISTRY/degraves/ci/pre-commit-base:v0.0.2
  stage: quality
  tags: ["aws-525-degraves"]
  script:
    - pre-commit run --all-files --show-diff-on-failure

unit_test:
  image: docker:git
  stage: test
  tags: ["aws-525-degraves"]
  script:

    # Duplicating `make test` in CI
    - MICROPYPATH=""
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/mp-lib/unittest"
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/mp-lib/argparse"
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/mp-lib/fnmatch"
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/mp-lib/os.path"
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/test_support"
    - MICROPYPATH="${MICROPYPATH}:/usr/lib/mock_machine"
    - MICROPYPATH="${MICROPYPATH}:.frozen"
    - MICROPYPATH="${MICROPYPATH}:''"
    - MICROPYCMD="MICROPYPATH=${MICROPYPATH} micropython-dev test/test_micropython_mdc200.py"
    - >
      docker run --rm -v $(pwd):/code -w /code
      -v $(pwd)/lib/micropython-lib/python-stdlib:/usr/lib/mp-lib
      -v $(pwd)/lib/test_support:/usr/lib/test_support
      -v $(pwd)/lib/micropython-mock-machine:/usr/lib/mock_machine
      micropython/unix bash -c "${MICROPYCMD}"
  artifacts:
    expire_in: 1 week
    when: always
